"""
© Copyright 2020-2021 HP Development Company, L.P.
SPDX-License-Identifier: GPL-2.0-only
"""

MLGIT_INIT = 'ml-git repository init'
MLGIT_REMOTE_ADD = 'ml-git repository remote %s add "%s"'
MLGIT_REMOTE_ADD_GLOBAL = 'ml-git repository remote %s add "%s" --global'
MLGIT_STORAGE_ADD = 'ml-git repository storage add %s --credentials=%s'
MLGIT_STORAGE_ADD_WITHOUT_CREDENTIALS = 'ml-git repository storage add %s'
MLGIT_STORAGE_ADD_WITH_ENDPOINT = 'ml-git repository storage add %s --credentials=%s --endpoint-url=%s'
MLGIT_STORAGE_ADD_WITH_TYPE = 'ml-git repository storage add %s --credentials=%s --type=%s'
MLGIT_ENTITY_INIT = 'ml-git %s init'
MLGIT_COMMIT = 'ml-git %s commit %s %s'
MLGIT_PUSH = 'ml-git %s push %s'
MLGIT_UPDATE = 'ml-git %s update'
MLGIT_REPOSITORY_UPDATE = 'ml-git repository update'
MLGIT_CHECKOUT = 'ml-git %s checkout %s'
MLGIT_ADD = 'ml-git %s add %s %s'
MLGIT_STATUS = 'ml-git %s status %s --full'
MLGIT_STATUS_DIRECTORY = 'ml-git %s status %s %s'
MLGIT_FETCH = 'ml-git %s fetch %s'
MLGIT_TAG_LIST = 'ml-git %s tag list %s'
MLGIT_RESET = 'ml-git %s reset %s'
MLGIT_REMOTE_FSCK = 'ml-git %s remote-fsck %s'
MLGIT_FSCK = 'ml-git %s fsck'
MLGIT_SHOW = 'ml-git %s show %s'
MLGIT_LIST = 'ml-git %s list'
MLGIT_BRANCH = 'ml-git %s branch %s'
MLGIT_CREATE = 'ml-git %s create %s'
MLGIT_CLONE = 'ml-git clone "%s" %s'
MLGIT_TAG_ADD = 'ml-git %s tag add %s %s'
MLGIT_IMPORT = 'ml-git %s import %s %s'
MLGIT_EXPORT = 'ml-git %s export %s'
MLGIT_UNLOCK = 'ml-git %s unlock %s %s'
MLGIT_STORAGE_DEL = 'ml-git repository storage del %s'
MLGIT_LOG = 'ml-git %s log %s %s'
MLGIT_CONFIG_SHOW = 'ml-git repository config show'
MLGIT_REMOTE_DEL = 'ml-git repository remote %s del'
MLGIT_STATUS_SHORT = 'ml-git %s status %s'
MLGIT_REPOSITORY_GC = 'ml-git repository gc'
MLGIT_MODELS_METRICS = 'ml-git models metrics %s %s'
MLGIT_CONFIG_REMOTE = 'ml-git repository remote config add "%s"'
MLGIT_CONFIG_PUSH = 'ml-git repository config push %s'
MLGIT_DIFF = 'ml-git %s diff %s %s %s'
