"""
© Copyright 2020 HP Development Company, L.P.
SPDX-License-Identifier: GPL-2.0-only
"""

doc = '''
  datasets:
    categories:
    - vision-computing
    - images
    mutability: strict
    manifest:
      files: MANIFEST.yaml
      storage: s3h://some-bucket
    name: datasets-ex
    version: 5
'''

output_messages = {
    'DEBUG_REMOVE_REMOTE': 'Removing remote from local repository [%s]',
    'DEBUG_BUILDING_STORAGE_LOG': 'Building the storage.log with these added files',
    'DEBUG_OBJECT_ALREADY_IN_STORAGE': 'Object [%s] already in %s storage',
    'DEBUG_STORAGE_AND_BUCKET': 'Storage [%s] ; bucket [%s]',
    'DEBUG_CHECKSUM_VERIFIED': 'Checksum verified for chunk [%s]',
    'DEBUG_KEY_PATH_ALREADY_EXISTS': 'Key path [%s] already exists in drive path [%s].',
    'DEBUG_CONNECT_PROFILE_AND_REGION': 'Connect - profile [%s] ; region [%s]',
    'DEBUG_CONNECTING_TO_STORAGE': 'Connecting to [%s]',
    'DEBUG_DOWNLOADING_FROM_BUCKET': 'Get - downloading [%s]  from bucket [%s] into file [%s]',
    'DEBUG_DELETING_FROM_BUCKET': 'Delete - deleting [%s] from bucket [%s]',
    'DEBUG_FILE_NOT_IN_LOCAL_REPOSITORY': 'File [%s] not present in local repository',
    'DEBUG_CONTAINER_ALREADY_EXISTS': 'Container %s already exists',
    'DEBUG_AZURE_CLI_NOT_FIND': 'Azure cli configurations not find.',
    'DEBUG_PUSH_BLOB_TO_STORAGE': 'LocalRepository: push blob [%s] to storage',
    'DEBUG_DELETE_BLOB_FROM_STORAGE': 'Delete blob [%s] from storage',
    'DEBUG_CHECK_IPLD': 'LocalRepository: check ipld [%s] in storage',

    'INFO_INITIALIZED_PROJECT': 'Initialized empty ml-git repository in %s',
    'INFO_ADD_REMOTE': 'Add remote repository [%s] for [%s]',
    'INFO_CHECKOUT_LATEST_TAG': 'Performing checkout on the entity\'s lastest tag (%s)',
    'INFO_CHECKOUT_TAG': 'Performing checkout in tag %s',
    'INFO_METADATA_INIT': 'Metadata init [%s] @ [%s]',
    'INFO_COMMIT_REPO': 'Commit repo[%s] --- file[%s]',
    'INFO_CHANGING_REMOTE': 'Changing remote from [%s] to [%s] for [%s]',
    'INFO_REMOVE_REMOTE': 'Removing remote repository [%s] from [%s].',
    'INFO_ADD_STORAGE': 'Add storage [%s://%s] with creds from profile [%s]',
    'INFO_ADD_STORAGE_WITHOUT_PROFILE': 'Add storage [%s://%s]',
    'INFO_INITIALIZING_RESET': 'Initializing reset [%s] [%s] of commit. ',
    'INFO_STARTING_GC': 'Starting the garbage collector for %s',
    'INFO_REMOVED_FILES': 'A total of %s files have been removed from %s',
    'INFO_RECLAIMED_SPACE': 'Total reclaimed space %s.',
    'INFO_ENTITY_DELETED': 'Entity %s was deleted',
    'INFO_PUT_STORED': 'Put - stored [%s] in bucket [%s] with key [%s]-[%s]',
    'INFO_WRONG_ENTITY_TYPE': 'Metrics cannot be added to this entity: [%s].',
    'INFO_DIRECTORY_STRUCTURE_WRONG': 'It was observed that the directories of this project follow the scheme of old versions of ml-git.\n'
                                      '\tTo continue using this project it is necessary to update the directories. Ml-git can do this update on its own.',
    'INFO_WANT_UPDATE_NOW': '\tDo you want to update your project now? (Yes/No) ',
    'INFO_PROJECT_UPDATE_SUCCESSFULLY': 'Project updated successfully',
    'INFO_ASSOCIATE_DATASETS': 'Associate datasets [%s]-[%s] to the %s.',
    'INFO_UPDATE_THE_PROJECT': 'It was observed that the directories of this project follow the scheme of old versions of ml-git.\n' +
                               '\tTo continue using this project it is necessary to update the directories.',
    'INFO_REMOVED_STORAGE': 'Removed storage [%s://%s] from configuration file.',

    'INFO_AKS_IF_WANT_UPDATE_PROJECT': '\tDo you want to update your project now? (Yes/No) ',
    'INFO_FILE_STORED_IN_BUCKET': 'Put - stored [%s] in bucket [%s] with key [%s]-[%s]',
    'INFO_PARANOID_MODE_ACTIVE': 'Paranoid mode is active - Downloading files: ',
    'INFO_FIXING_CORRUPTED_FILES_IN_STORAGE': 'Fixing corrupted files in remote storage',
    'INFO_EXPORTING_TAG': 'Exporting tag [%s] from [%s] to [%s].',

    'INFO_ALREADY_IN_RESPOSITORY': 'You already are in a ml-git repository',
    'ERROR_NOT_IN_RESPOSITORY': 'You are not in an initialized ml-git repository.',
    'ERROR_PATH_ALREAD_EXISTS': 'The path [%s] already exists and is not an empty directory.',
    'ERROR_UNABLE_TO_FIND': 'Unable to find %s. Check the remote repository used.',
    'ERROR_UNABLE_TO_FIND_REMOTE_REPOSITORY': 'Unable to find remote repository. Add the remote first.',
    'INFO_ADDING_PATH': '%s adding path',
    'INFO_ADDING_PATH_MODELS': 'models adding path',
    'INFO_ADDING_PATH_LABELS': 'labels adding path',
    'INFO_MLGIT_PULL': 'Pull [%s]',
    'ERROR_AMOUNT_PARAMETER_SHOULD_BE_SMALLER_GROUP_SIZE': 'The amount parameter should be smaller than the group size.',
    'ERROR_GROUP_SIZE_PARAMETER_SHOULD_BE_SMALLER_LIST_SIZE': 'The group size parameter should be smaller than the file list size.',
    'ERROR_START_PARAMETER_SHOULD_BE_SMALLER_THAN_STOP': 'The start parameter should be smaller than the stop.',
    'ERROR_STOP_PARAMETER_SHOULD_BE_SMALLER_LIST_SIZE': 'The stop parameter should be smaller than or equal to the file list size.',
    'ERROR_STEP_PARAMETER_SHOULD_BE_SMALLER_STOP': 'The step parameter should be smaller than the stop.',
    'ERROR_GROUP_SIZE_PARAMETER_SHOULD_BE_GREATER_ZERO': 'The group size parameter should be greater than zero.',
    'ERROR_FREQUENCY_PARAMETER_SHOULD_BE_GREATER_ZERO': 'The frequency parameter should be greater than zero.',
    'ERROR_AMOUNT_PARAMETER_SHOULD_BE_SMALLER_FREQUENCY': 'The amount parameter should be smaller than the frequency.',
    'ERROR_FREQUENCY_PARAMETER_SHOULD_BE_SMALLER_LIST_SIZE': 'The frequency  parameter should be smaller than the file list size.',
    'ERROR_PERMISSION_DENIED_INITIALIZE_DIRECTORY': 'Permission denied. You need write permission to initialize ml-git in this directory.',
    'INFO_NO_NEW_DATA_TO_ADD': 'There is no new data to add',
    'INFO_EXPORTING_TAG': 'Exporting tag [%s] from [%s] to [%s].',
    'INFO_REMOTE_FSCK_FIXED': 'remote-fsck -- fixed   : ipld[%d] / blob[%d]',
    'INFO_CORRUPTED_FILES_TOTAL': 'Total of corrupted files: %d',
    'INFO_PROJECT_CREATED': 'Project Created.',
    'INFO_SUCCESS_LOAD_CONFIGURATION': 'Successfully loaded configuration files!',
    'ERROR_AMOUNT_FREQUENCY_REQUIRES_POSITIVE': 'The --random-sample=<amount:frequency> --seed=<seed>: requires positive integer values.',
    'ERROR_AMOUNT_GROUP_REQUIRES_POSITIVE': 'The --group-sample=<amount:group-size> --seed=<seed>: requires positive integer values.',
    'ERROR_START_STOP_REQUIRES_POSITIVE': 'The --range-sample=<start:stop:step> or  --range-sample=<start:stop>: requires positive integer values.',
    'ERROR_AMOUNT_PARAMETER_SHOULD_BE_GREATER_ZERO': 'The amount parameter should be greater than zero.',
    'INFO_NOT_READY_REMOTE_REPOSITORY': 'Could not read from remote repository.',
    'INFO_PATH_NOT_EMPTY': 'The path [%s] is not an empty directory. Consider using --folder to create an empty folder.',
    'ERROR_FOLDER_PERMISSION_DENIED': 'Permission denied in folder',
    'INFO_MLGIT_TWO_VALUES': '2.00/2.00',
    'ERROR_NO_CURRENT_TAG_FOR': 'No current tag for [%s]. commit first.',
    'INFO_TAG_ALREDY_EXISTS': 'tag \'%s\' already exists',
    'INFO_CALLING_HEADOBJECT': 'when calling the HeadObject operation: Forbidden',
    'INFO_CREATE_TAG_SUCCESS': 'Create Tag Successfull',
    'INFO_MISSING_DESCRIPTOR_FILES': '%d missing descriptor files. Consider using the --thorough option.',
    'INFO_MISSING_DESCRIPTOR_FILES_DOWNLOAD': '%d missing descriptor files. Download:',
    'ERROR_MUTABILITY_CANNOT_CHANGE': 'Spec mutability cannot be changed.',
    'INFO_CORRUPTED_CANNOT_BE_ADD': 'The following files cannot be added because they are corrupted:',
    'INFO_CHECKOUT_BARE_MODE': 'Checkout in bare mode done.',
    'INFO_FILE_ALREADY_EXISTS_REPOSITORY': 'The file %s already exists in the repository. If you commit, the file will be overwritten.',
    'INFO_MUTABILITY_CANNOT_BE_STRICT': 'You cannot use this command for this entity because mutability cannot be strict.',
    'INFO_PERMISSIONS_CHANGED_FOR': 'The permissions for %s have been changed.',
    'INFO_FILE_NOT_FOUND': 'File %s not found',
    'INFO_TAG': 'Tag: %s',
    'INFO_MESSAGE': 'Message: %s',
    'INFO_FILES_TOTAL': 'Total of files: %d',
    'INFO_WORKSPACE_SIZE': 'Workspace size: %s',
    'INFO_ADDED_FILES': 'Added files [%s]',
    'INFO_DELETED_FILES': 'Deleted files [%s]',
    'INFO_FILES_SIZE': 'Files size: %s',
    'INFO_AMOUNT_SIZE': 'Amount of files: %s',
    'INFO_NOT_INITIALIZED': 'The %s doesn\'t have been initialized.',
    'INFO_NONE_ENTITY_ANAGED': 'You don\'t have any entity being managed.',
    'INFO_ENTITY_NAME_EXISTS': 'An entity with that name already exists.',
    'INFO_EXCLUSIVE_IMPORT_ARGUMENT': 'The argument `import` is mutually exclusive with argument',
    'INFO_EXCLUSIVE_CREDENTIALS_PATH_ARGUMENT': 'The argument `credentials_path` is required if `import-url` is used.',
    'INFO_INVALID_URL': 'Invalid url: [%s]',
    'INFO_UNZIPPING_FILES': 'Unzipping files',
    'INFO_NO_SUCH_OPTION': 'Error: no such option: --sample-type',
    'INFO_NOT_INITIALIZED_METADATA': 'Could not initialize metadata for %s.',
    'INFO_CANNOT_ADD_NEW_DATA_AN_ENTITY': 'You cannot add new data to an entity that is based on a checkout with the --sampling option.',
    'INFO_INITIALIZING_PROJECT': 'Initializing the project with global settings',
    'INFO_ARE_NOT_IN_INITIALIZED_PROJECT': 'You are not in an initialized ml-git repository and do not have a global configuration.',
    'INFO_NOT_GIT_REPOSITORY': 'fatal: not a git repository (or any of the parent directories): .git',
    'INFO_PATHSPEC_KNOWN_GIT': 'error: pathspec \'%s\' did not match any file(s) known to git',
    'INFO_UNABLE_AZURE_CONNECTION': 'Unable to connect to the Azure storage.',
    'INFO_ALREADY_EXISTS': 'Tag [%s] already exists in the ml-git repository.',
    'INFO_COULD_NOT_UPDATE_METADATA': 'Could not update metadata. Check your remote configuration.',

    'INFO_CREATE_ABORTED': 'Create command aborted!',
    'INFO_ALREAD_IN_REPOSITORY': 'You already are in a ml-git repository (%s)',
    'INFO_NO_FILES_COMMIT_FOR': 'No files to commit for [%s]',
    'INFO_ADDING_PATH_TO': '%s adding path [%s] to ml-git index',
    'INFO_STATUS_OF': '%s: status of ml-git index for [%s]',
    'INFO_NO_HEAD_FOR': 'No HEAD for [%s]',
    'INFO_INITIALIZING_DATASET_DOWNLOAD': 'Initializing related dataset download',
    'INFO_INITIALIZING_LABELS_DOWNLOAD': 'Initializing related labels download',
    'INFO_ALREADY_TAG': 'already at tag [%s]',
    'INFO_SPEC_NOT_HAVE_MUTABILITY': 'The spec does not have the \'mutability\' property set. Default: strict.',
    'INFO_STARTING_INTEGRITY_CHECK': 'Starting integrity check on [%s]',
    'INFO_REMOVING_CORRUPTED_FILES': 'Removing %s corrupted files',
    'INFO_GETTING_FILE': 'Getting file [%s] from local index',
    'INFO_NO_BLOBS_TO_PUSH': 'No blobs to push at this time.',
    'INFO_CORRUPTED_FILES': 'Corrupted files: %d',
    'INFO_REMOTE_FSCK_TOTAL': 'remote-fsck -- total   : ipld[%d] / blob[%d]',
    'INFO_LISTING_BLOBS': '\nListing blobs in container:',
    'INFO_FILE_LOCATED_TRASH': 'File [{}] located in trash.',
    'WARN_CANNOT_INITIALIZE_METADATA_FOR': 'Could not initialize metadata for %s. %s',
    'WARN_WORKER_EXCEPTION': 'Worker exception - [%s] -- retry [%d]',
    'WARN_NOT_EXIST_FOR_RELATED_DOWNLOAD': 'Repository: the %s does not exist for related download.',
    'WARN_NOT_FOUND': '[%s] Not found!',
    'WARN_FILE_EXISTS_IN_REPOSITORY': 'The file %s already exists in the repository. If you commit, the file will be overwritten.',

    'ERROR_WITHOUT_TAG_FOR_THIS_ENTITY': 'No entity with that name was found.',
    'ERROR_MULTIPLES_ENTITIES_WITH_SAME_NAME': 'You have more than one entity with the same name. Use one of the following tags to perform the checkout:\n',
    'ERROR_WRONG_VERSION_NUMBER_TO_CHECKOUT': 'The version specified for that entity does not exist. Last entity tag:\n\t%s',
    'ERROR_UNINITIALIZED_METADATA': 'You don\'t have any metadata initialized',
    'ERROR_REMOTE_UNCONFIGURED': 'Remote URL not found for [%s]. Check your configuration file.',
    'ERROR_ENTITY_NOT_FOUND': 'Entity type [%s] not found in your configuration file.',
    'ERROR_REMOTE_NOT_FOUND': 'Remote URL not found.',
    'ERROR_MISSING_MUTABILITY': 'Missing option "--mutability".  Choose from:\n\tstrict,\n\tflexible,\n\tmutable.',
    'ERROR_SPEC_WITHOUT_MUTABILITY': 'You need to define a mutability type when creating a new entity. '
                                     'Your spec should look something like this:' + doc,
    'ERROR_AWS_KEY_NOT_EXIST': 'The AWS Access Key Id you provided does not exist in our records.',
    'ERROR_BUCKET_DOES_NOT_EXIST': 'This bucket does not exist -- [%s]',
    'ERROR_INVALID_ENTITY_TYPE': 'Invalid entity type. Valid values are:',
    'ERROR_INVALID_STATUS_DIRECTORY': 'The directory informed is invalid.',
    'ERROR_OBJECT_NOT_FOUND': 'Object [%s] not found',
    'ERROR_NO_SUCH_OPTION': 'no such option: %s',
    'ERROR_INVALID_VALUE_FOR': 'Error: Invalid value for "%s": %s',
    'ERROR_NEED_UPDATE_PROJECT': 'To continue using this project it is necessary to update it.',
    'ERROR_PROJECT_NEED_BE_UPDATED': 'To continue using this project it is necessary to update it.',
    'ERROR_UNKNOWN_STORAGE_TYPE': 'Unknown data storage type [%s], choose one of these %s.',
    'ERROR_CORRPUTION_DETECTED': 'Corruption detected for chunk [%s] - got [%s]',
    'ERROR_DRIVE_PATH_NOT_FOUND': 'Drive path [%s] not found.',
    'ERROR_NOT_FOUND': '[%s] not found.',
    'ERROR_FILE_COULD_NOT_BE_UPLOADED': 'The file could not be uploaded: [%s]',
    'ERROR_AUTHETICATION_FAILED': 'Authentication failed',
    'ERROR_BUCKET_NOT_CONFIGURED': 'Put - bucket [%s] not configured with Versioning',
    'ERROR_AZURE_CREDENTIALS_NOT_FOUND': 'Azure credentials could not be found. See the ml-git documentation for how to configure.',
    'ERROR_WITHOUT_STORAGE': 'No storage for [%s]',
    'ERROR_CONFIG_PROFILE_NOT_FOUND': 'The config profile (%s) could not be found',

    'WARN_HAS_CONFIGURED_REMOTE': 'YOU ALREADY HAS A CONFIGURED REMOTE. All data stored in this repository will be sent to the new one on the first push.',
    'WARN_STORAGE_NOT_IN_CONFIG': 'Storage [%s://%s] not found in configuration file.',
    'WARN_EXCPETION_CREATING_STORAGE': 'Exception creating storage -- Configuration not found for bucket [%s]. '
                                       'The available buckets in config file for storage type [%s] are: %s',
    'WARN_REMOVING_FILES_DUE_TO_FAIL': 'Removing %s files from storage due to a fail during the push execution.'
}
